# Generated by Django 5.0 on 2024-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('salary_from', models.IntegerField(blank=True, null=True)),
                ('salary_to', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('date_posted', models.DateTimeField()),
                ('skills', models.TextField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
